#!/usr/bin/env ruby

require_relative 'app'

def main
  puts "Welcome to the School Library App!\n"
  app = App.new
  app.run
end

def options(num)
  case num
  when 1
    list_all_books
  when 2
    list_all_people
  when 3
    create_person
  when 4
    create_book
  when 5
    create_rental
  when 6
    list_rentals_by_id
  end
end

def extra_options(num)
  case num
  when 7
    list_all_students
  when 8
    list_all_teachers
  when 9
    exit
  end
end

main
