#!/usr/bin/env ruby

require_relative 'app'

def main
  puts "Welcome to the School Library App!\n"
  app = App.new
  app.run
end


def prompt_user
  puts "
        Please choose an option by entering a number from below:\n
        1 - List all books
        2 - List all people
        3 - Create a person
        4 - Create a book
        5 - Create a rental
        6 - List all rentals for a given person (id)
        7 - Exit"

  answer = gets.chomp.to_i

  case answer
  when 4
    puts 'Enter the title of the book:'
    title = gets.chomp
    puts 'Enter the author of the book:'
    author = gets.chomp
    puts "The book \'#{title}\' by #{author} is created successfully!"
   create_book(title, author)
  when 1
    puts "Books list:\n\n"
    list_all_books
  end
  prompt_user
end

main
